config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'checkout', to: "checkout#index"
  root to: "hello#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def index

  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/checkout/index.erb
<h1>You got to the checkout, but the music is still playing.</h1>

app/views/hello/index.erb
<%= video_tag("//dh7awlc6834tn.cloudfront.net/Turbo-Rails-Teaser-Vid.mp4",
              controls: true,
              autoplay: :autoplay,
              playsinline: true,
              loop: true,
              style: "width: 90%")
%>



<br />

Click "play" button control above, then...

<h1>
<%= link_to "Let's go >>>>>", checkout_path %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TR004</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>